blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/atelier-socle/swift-gherkin-testing/discussions
    about: Ask questions and get help from the community
